import type { EngineError } from "./types";

export const copy = {
  siteName: "WoW Forever Talents",
  header: {
    brand: "WoW Forever",
    brandSub: "Simulateur de talents",
    calc: "Calculateur",
    how: "Guide",
    sources: "Sources",
    badge: "Aperçu BlizzCon",
  },
  hero: {
    label: "Préparez votre prochaine répartition",
    titleBefore: "Calculateur de talents",
    titleEm: "WoW Forever",
    body: "Planifiez un build pour chacune des neuf classes. Comparez les changements depuis Classic, enregistrez votre setup et partagez chaque point.",
    meta: ["9 classes", "51 points de talents", "Gratuit · Sans compte"],
  },
  calculator: {
    character: "Personnage",
    treesHeading: "Arbres de talents {class}",
    pointsBySpec: "Points par spécialisation",
    level: "Niveau",
    levelAria: "Niveau du personnage",
    levelSet: "Niveau défini à {level}",
    pointsLeft: "points restants",
    pointsLeftOne: "point restant",
    pointsOf: "sur {budget}",
    compare: "Comparer à Classic",
    reset: "Tout réinitialiser",
    resetAll: "Tous les points ont été rendus",
    resetTree: "{tree} a été réinitialisé",
    myBuilds: "Mes builds",
    myBuildsCount: "Mes builds ({count})",
    copyBuild: "Copier le build",
    copiedShort: "Copié",
    copied: "Lien du build copié",
    copyManual: "Copiez le lien dans le champ ci-dessous",
    preparing: "Préparation du planificateur…",
    begin: "Votre histoire commence ici",
    draftRestored: "Brouillon restauré",
    sharedLoaded: "Build partagé chargé",
    keptUnchanged: "Le lien n’a pas pu être chargé ; la répartition actuelle est conservée",
    storageUnavailable: "Le stockage local n’est pas disponible",
    storageShort: "Brouillon non enregistré",
    draftSaved: "Brouillon enregistré dans ce navigateur",
    restoring: "Restauration du brouillon…",
    originalKept: "Lien d’origine conservé",
    requiredLevel: "Niveau requis",
    legendNew: "Nouveau dans Forever",
    legendChanged: "Modifié (texte, rangs ou position)",
    legendMoved: "Déplacé, même effet",
    legendUnchanged: "Grisé = inchangé depuis Classic",
    legendHint: "Le texte Classic apparaît dans chaque infobulle.",
    treeTabs: "Choisir un arbre",
    previewFooter: "Aperçu BlizzCon ·",
    sourcesLink: "Données et sources",
    readAll: "Lire tous les talents {class}",
    shareBar: "Partager le build",
    shareEyebrow: "Un lien. Chaque point de talent.",
    shareLead: "Partagez votre répartition exacte.",
    shareInput: "Lien du build",
    copyLink: "Copier le lien",
    share: "Partager",
    shareTitle: "Build {class} — WoW Forever",
    shareFailed: "Le partage a échoué",
    loadErrorTitle: "Impossible de charger ce build",
    originalLink: "Lien d’origine",
    startFresh: "Recommencer à zéro",
    fresh: "Nouvelle répartition",
    editBlocked: "Modifications bloquées tant que le lien n’est pas résolu",
    touchAgain: "Touchez de nouveau pour apprendre un rang",
    rankLearned: "Rang appris : {talent}",
    pointRefunded: "Rang retiré : {talent}",
    saveUnavailable: "Impossible d’enregistrer sans stockage local",
    savedNamed: "Build « {name} » enregistré",
    loadedNamed: "Build « {name} » chargé",
    deletedNamed: "Build « {name} » supprimé",
    dialogEyebrow: "Builds nommés",
    dialogTitle: "Mes builds {class}",
    dialogIntro: "Les noms restent sur cet appareil et ne sont pas inclus dans les liens partagés.",
    buildName: "Nom du build",
    namePlaceholder: "ex. {class} 31/20",
    saveBuild: "Enregistrer",
    closeSaves: "Fermer",
    emptySaves: "Aucun build nommé pour cette classe.",
    load: "Charger",
    deleteNamed: "Supprimer {name}",
  },
  tree: {
    aria: "Arbre {tree}",
    reset: "Réinitialiser {tree}",
    node: "{talent}, rang {rank} sur {max}",
    change: "Statut : {status}",
    alsoMoved: "Également déplacé",
    story: "Votre histoire commence ici",
    investedOne: "{points} point investi",
    investedMany: "{points} points investis",
  },
  detail: {
    emptyEyebrow: "Chaque choix façonne le build.",
    emptyTitle: "Survolez ou sélectionnez un talent",
    emptyBody: "Explorez ses rangs, prérequis et changements par rapport à Classic.",
    clickKey: "Clic",
    clickLearn: "Apprendre un rang",
    rightKey: "Clic droit",
    rightRefund: "Rembourser un rang",
    touchHint: "Sur tactile, touchez pour inspecter, puis touchez encore pour apprendre.",
    selected: "Détail du talent",
    close: "Fermer",
    passive: "Passif",
    active: "Actif",
    rank: "Rang",
    currentRank: "Rang actuel",
    firstRank: "Premier rang",
    nextRank: "Rang suivant ({rank})",
    unverified: "Rang {rank} non vérifié",
    unverifiedBody: "Ce rang n’a pas été lu dans la démo BlizzCon. Les valeurs manquantes ne sont pas inventées.",
    rankReference: "Texte le plus proche (rang {rank}) :",
    sourceEstimate: "Estimation de source",
    sourceNote: "Note : {note}",
    classic: "Classic",
    unchanged: "Inchangé",
    newTalent: "Ce talent n’existait pas dans Classic.",
    moved: "déplacé",
    classicMeta: "{name} · {tree} · rangs : {max}",
    movedFrom: "Déplacé de {fromTree} (ligne {fromRow}, colonne {fromCol}) vers {toTree} (ligne {toRow}, colonne {toCol}).",
    rowReq: "Ligne {row} : {needed} points dans les lignes précédentes de cet arbre.",
    requiresRanks: "Requiert {max}/{max} {talent}.",
    unlearn: "Oublier",
    learn: "Apprendre",
    refundTitle: "Rembourser un rang",
    learnTitle: "Apprendre un rang",
  },
  errors: {
    "invalid-build": "Build invalide.",
    "wrong-class": "Ce lien appartient à une autre classe.",
    "invalid-level": "Niveau invalide.",
    "missing-trees": "Les trois arbres sont requis.",
    "tree-mismatch": "L’arbre {tree} ne correspond pas aux données actuelles.",
    "invalid-rank": "Rang invalide pour {talent}.",
    "talent-gate": "Prérequis non respecté pour {talent}. {cause}",
    "over-budget": "Trop de points pour le niveau {level} (budget {budget}).",
    "unknown-talent": "Talent inconnu.",
    "max-rank": "Rang maximum déjà atteint.",
    "no-points-left": "Plus aucun point disponible.",
    "no-points-to-refund": "Aucun rang à rembourser.",
    "refund-blocked": "Remboursement bloqué : {cause}",
    "requires-row-points": "Il faut {needed} points dans les lignes précédentes de {tree}.",
    "requires-prerequisite": "Il faut {max}/{max} {talent}.",
    "missing-prerequisite": "Prérequis manquant dans les données.",
    "link-too-long": "Lien trop long.",
    "link-damaged": "Lien endommagé ou incomplet.",
    "unsupported-format": "Format de lien non pris en charge.",
    "wrong-data-version": "Ce lien utilise une autre version des données.",
    "storage-unavailable": "Stockage local indisponible.",
    "draft-write-failed": "Impossible d’enregistrer le brouillon.",
    "saved-list-damaged": "Liste de builds endommagée.",
    "saved-read-failed": "Impossible de lire les builds enregistrés.",
    "save-failed": "Enregistrement impossible.",
    "invalid-build-name": "Donnez un nom de 1 à 80 caractères.",
  } satisfies Record<EngineError["code"], string>,
  how: {
    title: "Comment utiliser le calculateur",
    intro: "Choisissez une classe, réglez le niveau, puis explorez un chemin à travers ses trois arbres. Les trois partagent le même budget de points. Vous pouvez inspecter un talent verrouillé avant de dépenser quoi que ce soit.",
    steps: [
      {
        n: "01",
        title: "Choisissez un arbre",
        body: "Chaque classe ouvre son calculateur. Un brouillon est conservé par classe : essayer Mage ne perd pas votre setup Guerrier. Le niveau 30 donne 21 points, le niveau 60 en donne 51.",
      },
      {
        n: "02",
        title: "Apprenez et remboursez",
        body: "Clic pour apprendre un rang, clic droit ou Maj+clic pour rembourser. Sur tactile, touchez pour inspecter puis touchez encore pour apprendre. Le panneau de détail affiche le rang actuel, le suivant, et tout prérequis bloquant.",
      },
      {
        n: "03",
        title: "Respectez les prérequis",
        body: "Chaque ligne plus profonde exige cinq points de plus dans les lignes précédentes du même arbre. Les flèches indiquent un prérequis à rang complet. Un remboursement qui casserait un talent plus profond est bloqué.",
      },
    ],
  },
  faq: {
    title: "Questions fréquentes",
    intro: "Réponses sur les données d’aperçu, les limites de points et les builds enregistrés.",
    items: [
      {
        q: "Ce calculateur est-il gratuit ?",
        a: "Oui. Les neuf classes, la comparaison Classic, les enregistrements locaux et les liens de build sont disponibles sans compte.",
      },
      {
        q: "Puis-je coller un build Classic Era ?",
        a: "Servez-vous-en comme point de départ, puis vérifiez chaque choix. Ce calculateur utilise les règles de l’aperçu BlizzCon : positions, effets et prérequis peuvent différer de Classic Era.",
      },
      {
        q: "Pourquoi mon build ne tient-il pas à un niveau plus bas ?",
        a: "Les points dépensés dépassent le nouveau budget. Remboursez d’abord, ou réinitialisez puis choisissez le niveau inférieur. Un changement refusé laisse la répartition intacte.",
      },
      {
        q: "Un build valide identifie-t-il les meilleurs talents ?",
        a: "Non. Le calculateur vérifie le budget et les prérequis. Il ne simule ni les dégâts ni l’équipement. Testez le build en jeu.",
      },
    ],
  },
  footer: {
    credit: "Données transcrites par talentsforever.com (CC BY 4.0) à partir des tooltips de la démo BlizzCon 2026. Noms, icônes et textes appartiennent à Blizzard Entertainment. Fan-made, non affilié à Blizzard.",
    note: "Les rangs manquants restent non vérifiés : aucune valeur n’est inventée pour combler les trous.",
  },
};

export function fill(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{([a-zA-Z]+)\}/g, (_, key: string) => String(vars[key] ?? ""));
}

export function formatError(error: EngineError): string {
  const template = copy.errors[error.code] ?? error.code;
  const vars: Record<string, string | number> = { ...error.params };
  if (error.params?.treeName && !vars.tree) vars.tree = error.params.treeName;
  if (error.params?.talentName && !vars.talent) vars.talent = error.params.talentName;
  if (error.cause) vars.cause = formatError(error.cause);
  return fill(template, vars);
}
